services:
  - type: web
    name: arduino_web
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn arduino_web.wsgi:application"
    plan: free
    branch: master
    autoDeploy: true
