services:
  - type: web
    name: arduino_web
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn arduino_web.wsgi:application"
    autoDeploy: true
